import discord
from discord import app_commands
from swapMod.plate_swap import NOT_A_SERIES


def install(core,engine):
    group=app_commands.Group(name='plateswap',description='Per-printer Swapmod A1m settings (A-series printers only)')
    async def admin(i):
        return await core.require(i,'plateswap')

    async def preview(i,title,detail,apply):
        class Confirm(core.OwnedView):
            def __init__(self):
                super().__init__(i.user.id);self.button('Confirm',self.confirm,discord.ButtonStyle.danger);self.button('Cancel',self.cancel)
            async def confirm(self,click):
                if not await admin(click):return
                if self.used:return
                self.used=True;self.stop();await click.response.defer()
                try:apply();text='Plate-swap workflow updated. No movement command was sent.'
                except ValueError as exc:text=str(exc)
                await click.edit_original_response(content=text,embed=None,view=None)
        view=Confirm();view.message=await i.followup.send(embed=core.card(title,detail),view=view,ephemeral=core.ephemeral(i),wait=True)

    @group.command(name='configure',description='Enable/disable an installed kit or update its magazine plate count')
    @app_commands.guild_only()
    @app_commands.choices(model=[app_commands.Choice(name=x,value=x) for x in ('A1 mini',)])
    async def configure(i:discord.Interaction,name:str,enabled:bool,model:str='A1 mini',spares:app_commands.Range[int,0,100]=0):
        if not await admin(i):return
        await i.response.defer(ephemeral=core.ephemeral(i))
        exact,_=core.resolve_name(name)
        if not exact:
            await i.followup.send('Choose a printer from autocomplete or enter its full management name.',ephemeral=core.ephemeral(i));return
        if enabled and not engine.plate_swap.available(exact):
            await i.followup.send(NOT_A_SERIES,ephemeral=core.ephemeral(i));return
        await preview(i,'Confirm plate-swap settings',f'{core.safe(exact)} • {"Enable" if enabled else "Disable"} • {model}\n{spares} blank plates loaded in the magazine.\nConfirm the matching kit is installed and this is the actual count. This resets plate checks and job approvals. Queue a batch generated by Swaplist for this kit. Plate changes within the batch are handled by that file; separate batches still require approval.',
            lambda:engine.plate_swap.configure(exact,enabled,model,spares,True,f'Discord {i.user.id}'))

    @group.command(name='check',description='Confirm the starting setup before a Swaplist batch')
    @app_commands.guild_only()
    async def check(i:discord.Interaction,name:str):
        if not await admin(i):return
        await i.response.defer(ephemeral=core.ephemeral(i))
        exact,_=core.resolve_name(name)
        if not exact:
            await i.followup.send('Choose a printer from autocomplete.',ephemeral=core.ephemeral(i));return
        if not engine.plate_swap.available(exact):
            await i.followup.send(NOT_A_SERIES,ephemeral=core.ephemeral(i));return
        def apply():
            engine.ready(exact);engine.plate_swap.verify(exact,True,f'Discord {i.user.id}')
        await preview(i,'Confirm Swapmod starting setup',f'{core.safe(exact)}\nI checked the starting setup against Swaplist instructions, loaded the required magazine plates, and cleared the ejection path. This does not perform a swap. Use /queuestart afterward.',apply)

    @group.command(name='approve',description='Approve a prepared Swaplist batch and its total plate count')
    @app_commands.guild_only()
    async def approve(i:discord.Interaction,job_id:str,plates:app_commands.Range[int,1,100]):
        if not await admin(i):return
        await i.response.defer(ephemeral=core.ephemeral(i))
        try:job=engine.store.get(job_id)
        except ValueError as exc:
            await i.followup.send(str(exc),ephemeral=core.ephemeral(i));return
        await preview(i,'Confirm prepared Swaplist batch',f'{core.safe(job["printer"])} • {core.safe(job["label"])}\nThis file was generated by Swaplist for Swapmod A1m and requires {plates} plates for the entire batch. I verified its filament mapping and starting setup. This is my confirmation; the application has not verified the G-code.',
            lambda:engine.plate_swap.approve_job(job_id,True,f'Discord {i.user.id}',plates))

    async def autocomplete(i,current):
        # Only A-series printers (A1 / A1 mini) can use Swapmod (#17).
        return [app_commands.Choice(name=core.display_name(n)[:100],value=core.display_name(n)) for n in core.names()
                if engine.plate_swap.available(n) and current.casefold() in (n+' '+core.display_name(n)).casefold()][:25]
    configure.autocomplete('name')(autocomplete);check.autocomplete('name')(autocomplete)
    core.bot.tree.add_command(group)
